import {
  Leaf,
  ShieldCheck,
  Recycle,
  Globe2,
  Cog,
  Truck,
  Building2,
  Fish,
  Star,
  Trees,
  Warehouse,
  Layers,
  Factory,
  Wrench,
  Award,
  Clock,
  ShieldPlus,
  Sparkles,
  ThumbsUp,
  Handshake,
  Rocket,
  Users,
  Boxes,
  ShieldAlert,
  LayoutPanelLeft,
  Spline,
  SquareStack,
  Package,
  Calendar,
  Building,
  MapPin,
  MessageCircle,
  Mail,
  Search,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  leaf: Leaf,
  shield: ShieldCheck,
  "shield-plus": ShieldPlus,
  "shield-alert": ShieldAlert,
  recycle: Recycle,
  globe: Globe2,
  cog: Cog,
  truck: Truck,
  building: Building2,
  "building-2": Building,
  fish: Fish,
  star: Star,
  trees: Trees,
  warehouse: Warehouse,
  layers: Layers,
  factory: Factory,
  wrench: Wrench,
  award: Award,
  clock: Clock,
  sparkles: Sparkles,
  "thumbs-up": ThumbsUp,
  handshake: Handshake,
  rocket: Rocket,
  users: Users,
  boxes: Boxes,
  "layout-panel-left": LayoutPanelLeft,
  spline: Spline,
  "square-stack": SquareStack,
  package: Package,
  calendar: Calendar,
  "map-pin": MapPin,
  "message-circle": MessageCircle,
  mail: Mail,
  search: Search,
};

export function Icon({
  name,
  className,
}: {
  name: string;
  className?: string;
}) {
  const Comp = iconMap[name] ?? Star;
  return <Comp className={className} aria-hidden="true" />;
}
