import { defineField, defineType } from "sanity";

export const product = defineType({
  name: "product",
  title: "Producto",
  type: "document",
  fields: [
    defineField({ name: "name", title: "Nombre", type: "string", validation: (r) => r.required() }),
    defineField({
      name: "slug",
      title: "Slug (URL)",
      type: "slug",
      options: { source: "name" },
      validation: (r) => r.required(),
    }),
    defineField({ name: "code", title: "Código", type: "string" }),
    defineField({
      name: "brand",
      title: "Marca",
      type: "string",
      options: { list: [{ title: "KD Pack", value: "kdpack" }] },
      initialValue: "kdpack",
    }),
    defineField({
      name: "category",
      title: "Categoría",
      type: "string",
      options: {
        list: [
          { title: "Agrícola (otros)", value: "agricola" },
          { title: "Cajas expo", value: "cajas-expo" },
          { title: "Cajas cosecheras", value: "cajas-cosecheras" },
          { title: "Forestal", value: "forestal" },
          { title: "Almacenaje", value: "almacenaje" },
          { title: "Pallets", value: "pallets" },
          { title: "Pesca", value: "pesca" },
          { title: "Acuícola", value: "acuicola" },
          { title: "Específicos", value: "especificos" },
          { title: "Encofrados", value: "encofrados" },
          { title: "Separadores", value: "separadores" },
          { title: "Tapas", value: "tapas" },
          { title: "Terminaciones", value: "terminaciones" },
          { title: "Alivianantes", value: "alivianantes" },
          { title: "Drenaje", value: "drenaje" },
        ],
      },
    }),
    defineField({
      name: "industries",
      title: "Industrias",
      description: "Selecciona una o más industrias a las que sirve este producto. Se usa para el filtro de Industria en /productos.",
      type: "array",
      of: [{ type: "string" }],
      options: {
        list: ["Agrícola", "Construcción", "Logística", "Forestal", "Pesca"],
      },
    }),
    defineField({ name: "productType", title: "Tipo de producto", type: "string" }),
    defineField({ name: "size", title: "Dimensiones", type: "string" }),
    defineField({ name: "material", title: "Material", type: "string" }),
    defineField({ name: "volumeLiters", title: "Volumen (litros)", type: "string" }),
    defineField({ name: "unitsPerPallet", title: "Unidades por pallet", type: "string" }),
    defineField({ name: "recyclable", title: "100% Reciclable", type: "boolean" }),
    defineField({ name: "reusable", title: "100% Reutilizable", type: "boolean" }),
    defineField({ name: "description", title: "Descripción", type: "text", rows: 3 }),
    defineField({
      name: "features",
      title: "Características",
      type: "array",
      of: [{ type: "string" }],
      options: {
        list: ["Apilable", "Plegable", "Con tapa", "Reforzado", "Ventilado", "Uso alimentario"],
      },
    }),
    defineField({ name: "image", title: "Imagen principal", type: "image", options: { hotspot: true } }),
    defineField({
      name: "gallery",
      title: "Fotos adicionales",
      description: "Sube más fotos del producto. Se muestran junto a la imagen principal en la ficha del producto.",
      type: "array",
      of: [{ type: "image", options: { hotspot: true } }],
    }),
    defineField({
      name: "documents",
      title: "Documentos (PDF)",
      description: "Certificados, fichas técnicas o guías. Cada uno aparece como un botón en la ficha del producto.",
      type: "array",
      of: [{ type: "productDocument" }],
    }),
    defineField({ name: "order", title: "Orden", type: "number" }),
  ],
  orderings: [
    { title: "Orden manual", name: "orderAsc", by: [{ field: "order", direction: "asc" }] },
  ],
  preview: {
    select: { title: "name", subtitle: "code", media: "image" },
  },
});
